// Generated by scripts/lib/survivor-actors.mjs; offsets and durations match Ranger.glb.
export const HERO_CLIPS = {
    "move": {
        "offset": 0,
        "count": 8,
        "duration": 0.9333333373069763,
        "loop": true
    },
    "attack": {
        "offset": 8,
        "count": 6,
        "duration": 0.5,
        "loop": false
    },
    "windup": {
        "offset": 14,
        "count": 4,
        "duration": 0.5333333611488342,
        "loop": false
    },
    "channel": {
        "offset": 18,
        "count": 4,
        "duration": 2.0999999046325684,
        "loop": true
    },
    "recovery": {
        "offset": 22,
        "count": 4,
        "duration": 0.4333333373069763,
        "loop": false
    },
    "hurt": {
        "offset": 26,
        "count": 4,
        "duration": 0.3333333432674408,
        "loop": false
    },
    "death": {
        "offset": 30,
        "count": 8,
        "duration": 2.4000000953674316,
        "loop": false
    },
    "idle": {
        "offset": 38,
        "count": 4,
        "duration": 2.5,
        "loop": true
    }
} as const;
export const HERO_POSES = 42;
