// Generated by scripts/lib/survivor-actors.mjs; skeletal clips match Ranger.glb.
export const HERO_CLIPS = {
    "move": {
        "duration": 0.9333333373069763,
        "loop": true
    },
    "attack": {
        "duration": 0.5,
        "loop": false
    },
    "windup": {
        "duration": 0.5333333611488342,
        "loop": false
    },
    "channel": {
        "duration": 2.0999999046325684,
        "loop": true
    },
    "recovery": {
        "duration": 0.4333333373069763,
        "loop": false
    },
    "hurt": {
        "duration": 0.3333333432674408,
        "loop": false
    },
    "death": {
        "duration": 2.4000000953674316,
        "loop": false
    },
    "idle": {
        "duration": 2.5,
        "loop": true
    }
} as const;
