export const SURFACE_RENDER_CHUNK_SIZE = 16;
export const SURFACE_SAMPLES_PER_TILE_INTERVAL = 4;
export const SURFACE_FIELD_CORE_SIZE =
    SURFACE_RENDER_CHUNK_SIZE * SURFACE_SAMPLES_PER_TILE_INTERVAL;
export const SURFACE_FIELD_GUTTER_TEXELS = 1;
export const SURFACE_FIELD_TEXTURE_SIZE =
    SURFACE_FIELD_CORE_SIZE + SURFACE_FIELD_GUTTER_TEXELS * 2;
export const SURFACE_FIELD_TEXEL_COUNT =
    SURFACE_FIELD_TEXTURE_SIZE * SURFACE_FIELD_TEXTURE_SIZE;
export const SURFACE_INFLUENCE_RADIUS_TILES = 2;
export const SURFACE_EFFECTIVE_WINDOW_SIZE =
    SURFACE_RENDER_CHUNK_SIZE + SURFACE_INFLUENCE_RADIUS_TILES * 2;
export const SURFACE_MAX_WATER_BODY_COUNT = 255;
export const SURFACE_CANONICAL_HEX_SIZE = 1;
export const SURFACE_TEXTURE_PAGE_LAYERS = 128;
export const SURFACE_WATER_COVERAGE_THRESHOLD = 128;
export const SURFACE_NARROW_RIVER_MAX_WIDTH_QUANTIZED = 24;
export const SURFACE_VEGETATION_COORDINATE_SCALE = 1024;
export const SURFACE_MAX_VEGETATION_SEEDS = SURFACE_RENDER_CHUNK_SIZE
    * SURFACE_RENDER_CHUNK_SIZE * 10;
export const SURFACE_COMPILER_REVISION = 3;
export const SURFACE_COMPILE_PROFILE_VERSION = 1;

export const SURFACE_COMPILE_PROFILE_V1 = Object.freeze({
    renderChunkSize: SURFACE_RENDER_CHUNK_SIZE,
    samplesPerTileInterval: SURFACE_SAMPLES_PER_TILE_INTERVAL,
    gutterTexels: SURFACE_FIELD_GUTTER_TEXELS,
    influenceRadiusTiles: SURFACE_INFLUENCE_RADIUS_TILES,
    textureLayerSize: SURFACE_FIELD_TEXTURE_SIZE,
    pageLayers: SURFACE_TEXTURE_PAGE_LAYERS,
    waterCoverageThreshold: SURFACE_WATER_COVERAGE_THRESHOLD,
    narrowRiverMaximumWidthQuantized: SURFACE_NARROW_RIVER_MAX_WIDTH_QUANTIZED,
    vegetationCoordinateScale: SURFACE_VEGETATION_COORDINATE_SCALE,
    maximumVegetationSeeds: SURFACE_MAX_VEGETATION_SEEDS
});
