import { expect, test } from "@playwright/test";

test("plays with baked actors, independent character/bag windows and complete keyboard HUD", async ({ page }) => {
    test.setTimeout(240_000);
    const errors: string[] = [];
    const loadedActors = new Set<string>();
    const loadedAtlases = new Set<string>();
    page.on("pageerror", error => errors.push(error.message));
    page.on("console", message => { if (message.type() === "error") errors.push(message.text()); });
    page.on("response", response => { if (/\/actors\/.*\.glb$/.test(response.url()) && response.ok()) loadedActors.add(response.url()); });
    page.on("response", response => { if (/\/actors\/.*\.png$/.test(response.url()) && response.ok()) loadedAtlases.add(response.url()); });
    await page.goto("/", { waitUntil: "domcontentloaded" });
    const application = page.locator(".survivor");
    await expect(application).toHaveAttribute("data-state", "ready", { timeout: 30_000 });
    expect(loadedActors.size).toBe(5);
    expect(loadedAtlases.size).toBe(20);
    const worldBounds = await page.locator("#survivor-world").boundingBox();
    expect(worldBounds?.width).toBe(page.viewportSize()!.width);
    expect(worldBounds?.height).toBe(page.viewportSize()!.height);
    await expect(page.getByTestId("region-status")).toHaveAttribute("data-difficulty", "normal");
    await expect(page.locator(".region-cell polygon")).toHaveCount(19);
    const mapBounds = await page.getByTestId("region-status").boundingBox();
    expect(mapBounds!.x).toBeGreaterThan(page.viewportSize()!.width / 2);
    expect(mapBounds!.y).toBeLessThan(40);
    expect((await page.getByLabel("法力", { exact: true }).boundingBox())!.y).toBeGreaterThan(page.viewportSize()!.height / 2);
    await expect.poll(async () => Number(await page.getByTestId("enemy-count").textContent())).toBeGreaterThan(0);
    await page.keyboard.press("KeyF");
    await expect(page.locator(".status-bar")).toContainText("自动施法 关");
    const beforeMana = await page.getByLabel("法力", { exact: true }).textContent();
    await page.keyboard.press("Digit1");
    await expect(page.getByLabel("法力", { exact: true })).not.toHaveText(beforeMana!);
    const tickBefore = Number(await page.getByTestId("elapsed-time").getAttribute("data-tick"));
    await page.keyboard.down("KeyW");
    await expect.poll(async () => Number(await page.getByTestId("elapsed-time").getAttribute("data-tick"))).toBeGreaterThan(tickBefore + 10);
    const pose = await page.evaluate(() => {
        const session = window.survivorApplication!.session as unknown as {
            view: { layer: { actors: { hero: { children: { morphTargetInfluences: number[] }[] }; enemies: unknown[][] } } }
        };
        const actors = session.view.layer.actors;
        return { weights: actors.hero.children[0].morphTargetInfluences, primitives: actors.enemies.map(pool => pool.length) };
    });
    expect(pose.weights.reduce((sum, value) => sum + value, 0)).toBeCloseTo(1);
    expect(pose.primitives).toEqual([1, 1, 1, 1]);
    await page.keyboard.up("KeyW");
    await page.keyboard.press("KeyP");
    await expect(application).toHaveAttribute("data-paused", "true");
    const pausedTick = Number(await page.getByTestId("elapsed-time").getAttribute("data-tick"));
    await page.waitForTimeout(250);
    expect(Number(await page.getByTestId("elapsed-time").getAttribute("data-tick"))).toBe(pausedTick);
    await page.screenshot({ path: "test-results/survivor-app/combat-hud.png" });

    await page.keyboard.press("KeyC");
    await expect(page.getByRole("dialog", { name: "角色", exact: true })).toBeVisible();
    await expect(page.locator(".equipment-slot")).toHaveCount(11);
    await expect(page.locator(".orb-socket")).toHaveCount(6);
    await expect(page.locator(".orb-socket:not(:disabled)")).toHaveCount(2);
    await expect(page.getByRole("button", { name: "宝珠槽 3，50级解锁", exact: true })).toBeDisabled();
    await page.getByRole("button", { name: "装备爆率说明", exact: true }).hover();
    await expect(page.getByRole("tooltip")).toContainText("寻宝分布");
    await expect(page.getByRole("tooltip")).toContainText("收益递减");
    await page.locator(".equipment-slot[data-slot=weapon]").click();
    const slotLayout = () => page.locator(".equipment-slot[data-slot=weapon]").evaluate(element => { const slot = element as HTMLElement; return { width: slot.offsetWidth, height: slot.offsetHeight, x: slot.offsetLeft, y: slot.offsetTop }; });
    const slotBefore = await slotLayout();
    await expect(page.locator(".equipment-inspector .gear-stars")).toHaveAttribute("aria-label", "1星");
    await expect(page.locator(".equipment-inspector .affix-list")).toHaveAttribute("aria-label", "2条词条");
    await page.getByRole("button", { name: "卸下装备", exact: true }).click();
    await expect(page.locator(".equipment-slot[data-slot=weapon]")).toHaveAttribute("aria-label", "武器：空");
    expect(await slotLayout()).toEqual(slotBefore);
    await page.keyboard.press("KeyB");
    const bag = page.getByRole("dialog", { name: "背包", exact: true });
    await expect(bag).toBeVisible();
    const character = page.getByRole("dialog", { name: "角色", exact: true });
    const characterBounds = (await character.boundingBox())!;
    const bagBounds = (await bag.boundingBox())!;
    expect(characterBounds.x + characterBounds.width).toBeLessThan(bagBounds.x);
    expect(bagBounds.x + bagBounds.width).toBeLessThanOrEqual(page.viewportSize()!.width);
    const characterMenu = page.getByRole("navigation", { name: "界面快捷键" }).getByRole("button", { name: /角色/ });
    await characterMenu.click();
    await expect(character).toHaveCount(0);
    await characterMenu.click();
    await expect(character).toBeVisible();
    await expect(bag.locator(".equipment-slot")).toHaveCount(0);
    await expect(bag.locator(".bag-inspector")).toHaveCount(0);
    const starter = bag.getByRole("article", { name: "守夜短弩，等级1", exact: true });
    await starter.hover();
    const tooltip = page.locator(".equipment-tooltip");
    await expect(tooltip.getByText("基础属性", { exact: true })).toBeVisible();
    await expect(tooltip.getByText("附加词条", { exact: true })).toBeVisible();
    await expect(tooltip.locator(".affix-list")).toHaveAttribute("aria-label", "2条词条");
    const itemOrder = () => bag.getByTestId("inventory-item").evaluateAll(cards => cards.map(card => ({
        id: Number(card.getAttribute("data-item-id")), level: Number(card.getAttribute("data-level")), rarity: card.getAttribute("data-rarity")!, kind: card.getAttribute("data-kind"), clearable: card.getAttribute("data-clearable") === "true"
    })));
    const beforeSort = await itemOrder();
    const rarities = ["common", "magic", "rare", "legendary", "diamond", "rainbow"];
    await bag.getByRole("button", { name: "一键整理", exact: false }).click();
    await expect.poll(itemOrder).toEqual([...beforeSort].sort((a, b) => rarities.indexOf(b.rarity) - rarities.indexOf(a.rarity) || b.level - a.level || a.id - b.id));
    await starter.click();
    await page.keyboard.press("Enter");
    await expect(page.locator(".equipment-slot[data-slot=weapon]")).not.toHaveAttribute("aria-label", "武器：空");
    expect(await slotLayout()).toEqual(slotBefore);
    const beforeClear = await itemOrder();
    const playerLevel = Number(await page.getByTestId("player-level").textContent());
    const cleanup = bag.getByRole("checkbox", { name: "自动清理低级劣装", exact: true });
    await expect(cleanup).not.toBeChecked();
    await cleanup.check();
    await expect(cleanup).toBeChecked();
    await expect.poll(itemOrder).toEqual(beforeClear.filter(item => item.kind !== "equipment" || item.level >= playerLevel || !item.clearable));
    await expect(page.locator(".equipment-slot[data-slot=weapon]")).not.toHaveAttribute("aria-label", "武器：空");
    // Checkbox focus must keep menu shortcuts available.
    await page.keyboard.press("KeyB"); await expect(bag).toHaveCount(0);
    await page.keyboard.press("KeyB"); await expect(cleanup).toBeChecked();
    await cleanup.uncheck();
    await expect(cleanup).not.toBeChecked();
    await page.screenshot({ path: "test-results/survivor-app/character-and-bag.png" });
    await page.setViewportSize({ width: 390, height: 844 });
    await expect(bag).toBeVisible();
    await expect(character).toBeHidden();
    const switcher = page.getByRole("navigation", { name: "切换窗口" });
    await switcher.getByRole("button", { name: "角色装备" }).click();
    await expect(character).toBeVisible();
    await expect(bag).toBeHidden();
    await page.locator(".equipment-slot[data-slot=weapon]").click();
    await page.getByRole("button", { name: "卸下装备", exact: true }).click();
    await switcher.getByRole("button", { name: "背包物品" }).click();
    await expect(starter).toBeVisible();
    await starter.click();
    const hiddenInventory = await itemOrder();
    await switcher.getByRole("button", { name: "角色装备" }).click();
    await page.keyboard.press("Delete");
    await switcher.getByRole("button", { name: "背包物品" }).click();
    expect(await itemOrder()).toEqual(hiddenInventory);
    await starter.getByRole("button", { name: "装备", exact: true }).click();
    await page.screenshot({ path: "test-results/survivor-app/narrow-inventory.png" });
    const dockBounds = (await page.getByRole("region", { name: "角色状态与技能" }).boundingBox())!;
    const menuBounds = (await page.getByRole("navigation", { name: "界面快捷键" }).boundingBox())!;
    expect(dockBounds.y + dockBounds.height).toBeLessThan(menuBounds.y);
    expect(dockBounds.x).toBeGreaterThanOrEqual(0);
    expect(dockBounds.x + dockBounds.width).toBeLessThanOrEqual(390);
    await page.getByRole("button", { name: "关闭背包", exact: true }).click();
    await expect(character).toBeVisible();
    await page.keyboard.press("KeyB");
    await page.setViewportSize({ width: 1280, height: 720 });
    await page.keyboard.press("Escape"); await expect(bag).toHaveCount(0);
    await page.keyboard.press("Escape"); await expect(page.getByRole("dialog", { name: "角色", exact: true })).toHaveCount(0);
    await page.keyboard.press("KeyM"); await expect(page.getByTestId("region-status")).toHaveClass(/expanded/);
    await page.keyboard.press("Escape"); await expect(page.getByTestId("region-status")).not.toHaveClass(/expanded/);
    await page.keyboard.press("KeyK"); await expect(page.getByRole("dialog", { name: "技能", exact: true })).toBeVisible();
    await page.keyboard.press("Escape");
    await page.keyboard.press("KeyI"); await expect(bag).toBeVisible();
    await page.keyboard.press("Escape"); await page.keyboard.press("Escape");
    await expect(application).toHaveAttribute("data-paused", "false");
    expect(errors).toEqual([]);
});

for (const file of ["Imp.glb", "Imp-normal.png"]) test(`reports failed actor resource ${file} and reloads after recovery`, async ({ page }) => {
    const model = `**/actors/${file}`;
    await page.route(model, route => route.fulfill({ status: 503, body: "actor unavailable" }));
    await page.goto("/", { waitUntil: "domcontentloaded" });
    await expect(page.locator(".survivor")).toHaveAttribute("data-state", "failed", { timeout: 30_000 });
    await expect(page.getByRole("alert")).toContainText(file);
    await page.unroute(model);
    await page.getByRole("button", { name: "重新尝试" }).click();
    await expect(page.locator(".survivor")).toHaveAttribute("data-state", "ready", { timeout: 30_000 });
    await expect(page.getByTestId("player-level")).toHaveText("1");
});
