import { expect, test } from "@playwright/test";

test("plays with baked actors, independent character/bag windows and complete keyboard HUD", async ({ page }) => {
    test.setTimeout(180_000);
    const errors: string[] = [];
    const loadedActors = new Set<string>();
    page.on("pageerror", error => errors.push(error.message));
    page.on("console", message => { if (message.type() === "error") errors.push(message.text()); });
    page.on("response", response => { if (/\/actors\/.*\.glb$/.test(response.url()) && response.ok()) loadedActors.add(response.url()); });
    await page.goto("/", { waitUntil: "domcontentloaded" });
    const application = page.locator(".survivor");
    await expect(application).toHaveAttribute("data-state", "ready", { timeout: 30_000 });
    expect(loadedActors.size).toBe(5);
    const worldBounds = await page.locator("#survivor-world").boundingBox();
    expect(worldBounds?.width).toBe(page.viewportSize()!.width);
    expect(worldBounds?.height).toBe(page.viewportSize()!.height);
    await expect(page.getByTestId("region-status")).toHaveAttribute("data-difficulty", "normal");
    await expect(page.locator(".region-cell polygon")).toHaveCount(19);
    const mapBounds = await page.getByTestId("region-status").boundingBox();
    expect(mapBounds!.x).toBeGreaterThan(page.viewportSize()!.width / 2);
    expect(mapBounds!.y).toBeLessThan(40);
    expect((await page.getByLabel("法力", { exact: true }).boundingBox())!.y).toBeGreaterThan(page.viewportSize()!.height / 2);
    await expect.poll(async () => Number(await page.getByTestId("enemy-count").textContent())).toBeGreaterThan(0);
    await page.keyboard.press("KeyF");
    await expect(page.locator(".status-bar")).toContainText("自动施法 关");
    const beforeMana = await page.getByLabel("法力", { exact: true }).textContent();
    await page.keyboard.press("Digit1");
    await expect(page.getByLabel("法力", { exact: true })).not.toHaveText(beforeMana!);
    const tickBefore = Number(await page.getByTestId("elapsed-time").getAttribute("data-tick"));
    await page.keyboard.down("KeyW");
    await expect.poll(async () => Number(await page.getByTestId("elapsed-time").getAttribute("data-tick"))).toBeGreaterThan(tickBefore + 10);
    await page.keyboard.up("KeyW");
    await page.keyboard.press("KeyP");
    await expect(application).toHaveAttribute("data-paused", "true");
    const pausedTick = Number(await page.getByTestId("elapsed-time").getAttribute("data-tick"));
    await page.waitForTimeout(250);
    expect(Number(await page.getByTestId("elapsed-time").getAttribute("data-tick"))).toBe(pausedTick);
    await page.screenshot({ path: "test-results/survivor-app/combat-hud.png" });

    await page.keyboard.press("KeyC");
    await expect(page.getByRole("dialog", { name: "角色", exact: true })).toBeVisible();
    await expect(page.locator(".equipment-slot")).toHaveCount(11);
    await expect(page.locator(".orb-socket")).toHaveCount(6);
    await expect(page.locator(".orb-socket:not(:disabled)")).toHaveCount(2);
    await expect(page.getByRole("button", { name: "宝珠槽 3，50级解锁", exact: true })).toBeDisabled();
    await page.getByRole("button", { name: "装备爆率说明", exact: true }).hover();
    await expect(page.getByRole("tooltip")).toContainText("寻宝分布");
    await expect(page.getByRole("tooltip")).toContainText("收益递减");
    await page.locator(".slot-weapon").click();
    const slotLayout = () => page.locator(".slot-weapon").evaluate(element => { const slot = element as HTMLElement; return { width: slot.offsetWidth, height: slot.offsetHeight, x: slot.offsetLeft, y: slot.offsetTop }; });
    const slotBefore = await slotLayout();
    await expect(page.locator(".gear-stars")).toHaveAttribute("aria-label", "1星");
    await expect(page.locator(".affix-list")).toHaveAttribute("aria-label", "2条词条");
    await page.getByRole("button", { name: "卸下装备", exact: true }).click();
    await expect(page.locator(".slot-weapon")).toHaveAttribute("aria-label", "武器：空");
    expect(await slotLayout()).toEqual(slotBefore);
    await page.keyboard.press("KeyB");
    const bag = page.getByRole("dialog", { name: "背包", exact: true });
    await expect(bag).toBeVisible();
    await expect(bag.locator(".equipment-slot")).toHaveCount(0);
    await expect(bag.locator(".bag-inspector")).toHaveCount(0);
    const starter = bag.getByRole("article", { name: "守夜短弩，等级1", exact: true });
    await expect(starter.getByText("基础属性", { exact: true })).toBeVisible();
    await expect(starter.getByText("附加词条", { exact: true })).toBeVisible();
    await expect(starter.locator(".affix-list")).toHaveAttribute("aria-label", "2条词条");
    const itemOrder = () => bag.getByTestId("inventory-item").evaluateAll(cards => cards.map(card => ({
        id: Number(card.getAttribute("data-item-id")), level: Number(card.getAttribute("data-level")), rarity: card.getAttribute("data-rarity")!, kind: card.getAttribute("data-kind")
    })));
    const beforeSort = await itemOrder();
    const rarities = ["common", "magic", "rare", "legendary", "diamond", "rainbow"];
    await bag.getByRole("button", { name: "一键整理", exact: false }).click();
    await expect.poll(itemOrder).toEqual([...beforeSort].sort((a, b) => rarities.indexOf(b.rarity) - rarities.indexOf(a.rarity) || b.level - a.level || a.id - b.id));
    await starter.click();
    await page.keyboard.press("Enter");
    await expect(page.locator(".slot-weapon")).not.toHaveAttribute("aria-label", "武器：空");
    expect(await slotLayout()).toEqual(slotBefore);
    const beforeClear = await itemOrder();
    const playerLevel = Number(await page.getByTestId("player-level").textContent());
    const cleanup = bag.getByRole("checkbox", { name: "自动清理低级装备", exact: true });
    await expect(cleanup).not.toBeChecked();
    await cleanup.check();
    await expect(cleanup).toBeChecked();
    await expect.poll(itemOrder).toEqual(beforeClear.filter(item => item.kind !== "equipment" || item.level >= playerLevel));
    await expect(page.locator(".slot-weapon")).not.toHaveAttribute("aria-label", "武器：空");
    // Checkbox focus must keep menu shortcuts available.
    await page.keyboard.press("KeyB"); await expect(bag).toHaveCount(0);
    await page.keyboard.press("KeyB"); await expect(cleanup).toBeChecked();
    await cleanup.uncheck();
    await expect(cleanup).not.toBeChecked();
    await page.screenshot({ path: "test-results/survivor-app/character-and-bag.png" });
    await page.keyboard.press("Escape"); await expect(bag).toHaveCount(0);
    await page.keyboard.press("Escape"); await expect(page.getByRole("dialog", { name: "角色", exact: true })).toHaveCount(0);
    await page.keyboard.press("KeyM"); await expect(page.getByTestId("region-status")).toHaveClass(/expanded/);
    await page.keyboard.press("Escape"); await expect(page.getByTestId("region-status")).not.toHaveClass(/expanded/);
    await page.keyboard.press("KeyK"); await expect(page.getByRole("dialog", { name: "技能", exact: true })).toBeVisible();
    await page.keyboard.press("Escape");
    await page.keyboard.press("KeyI"); await expect(bag).toBeVisible();
    await page.keyboard.press("Escape"); await page.keyboard.press("Escape");
    await expect(application).toHaveAttribute("data-paused", "false");
    expect(errors).toEqual([]);
});

test("reports a failed actor download and can reload the same world after the resource recovers", async ({ page }) => {
    const model = "**/actors/Skeleton_Rogue.glb";
    await page.route(model, route => route.fulfill({ status: 503, body: "actor unavailable" }));
    await page.goto("/", { waitUntil: "domcontentloaded" });
    await expect(page.locator(".survivor")).toHaveAttribute("data-state", "failed", { timeout: 30_000 });
    await expect(page.getByRole("alert")).toContainText("Skeleton_Rogue.glb");
    await page.unroute(model);
    await page.getByRole("button", { name: "重新尝试" }).click();
    await expect(page.locator(".survivor")).toHaveAttribute("data-state", "ready", { timeout: 30_000 });
    await expect(page.getByTestId("player-level")).toHaveText("1");
});
