import type { CombatRewards } from "../../src/core/CombatRewards";
import { expect, test } from "@playwright/test";
import { createStarterEquipment, withEquipmentAffixes, type Equipment } from "../../src/core/Equipment";
import { createAffixItem } from "../../src/core/AffixItem";
import { createOrb } from "../../src/core/Orbs";
import { EMPTY_SPIRIT_REALM } from "../../src/core/SpiritRealm";
import type { CombatSimulation } from "../../src/core/CombatSimulation";
import type { InventoryItem } from "../../src/core/InventoryItem";
import type { CombatWorld } from "../../src/core/CombatWorld";
import { enterWilds, inspectCombatWorker, combatWorker, pauseCombat, advanceCombat } from "../helpers/browserCombat";
import { isBrowserConsoleFailure } from "../helpers/browserConsole";

test("crafting confirms destructive changes, supports affix dragging and persists spirit growth across reload and restart", async ({ page }, testInfo) => {
    test.setTimeout(180_000);
    const errors: string[] = [];
    page.on("pageerror", error => errors.push(error.message));
    page.on("console", message => { if (isBrowserConsoleFailure(message.type(), message.text())) errors.push(message.text()); });
    await inspectCombatWorker(page); await page.goto("/", { waitUntil: "domcontentloaded" });
    await page.getByRole("button", { name: "开始新游戏", exact: true }).click();
    await enterWilds(page);
    await expect(page.locator(".survivor")).toHaveAttribute("data-state", "ready", { timeout: 30_000 });
    await pauseCombat(page);
    const gear = (id: number, name: string, damage: number): Equipment => ({ ...withEquipmentAffixes(createStarterEquipment(), [
        { stat: "damage", value: damage, rarity: "rare" }, { stat: "armor", value: 3, rarity: "magic" }
    ]), id, name, locked: false, revision: 0 });
    const source = gear(10, "提取试炼弓", 40), target = gear(11, "目标长弓", 3), inheritance = { ...gear(12, "先祖长弓", 80), stars: 3 as const, rarity: "diamond" as const };
    const items: InventoryItem[] = [source, target, inheritance, { ...createAffixItem(20, { stat: "goldBonus", value: .5, rarity: "rare" }), size: 2 }, createOrb(30, "rare", "fortune")];
    await combatWorker(page).evaluate(({ items, realm }) => {
        const simulation = (self as unknown as { fixtureSimulation: CombatSimulation }).fixtureSimulation;
        const fixture = simulation as unknown as { rewards: CombatRewards; inventory: InventoryItem[]; orbDust: number; entities: CombatWorld; resolveImpacts(): void };
        fixture.inventory = items; fixture.rewards.gold = 100_000; fixture.orbDust = 1000; fixture.rewards.nextItemId = 1000; fixture.rewards.spiritRealm = realm;
        const e = fixture.entities, slot = e.enemies.slots[0], source = e.world.ids[e.player], target = e.world.ids[slot];
        e.vitality.damage(source, target, e.vitals.health[slot], simulation.tick, 0);
        e.vitality.defeat(source, target, simulation.tick, 0);
        fixture.resolveImpacts();
    }, { items, realm: { ...EMPTY_SPIRIT_REALM, souls: 999, revision: 1 } });
    await advanceCombat(page);
    await page.keyboard.press("KeyJ");
    const forge = page.getByRole("dialog", { name: "打造", exact: true });
    await forge.locator('[data-craft-equipment="10"]').click();
    await forge.getByRole("button", { name: "提取选中词条", exact: true }).click();
    await expect(page.getByRole("dialog", { name: "确认物品操作" })).toContainText("销毁");
    await expect(page.getByRole("button", { name: "继续核对", exact: true })).toHaveCount(0);
    await page.getByRole("checkbox", { name: "以后提取词条不再显示确认" }).check();
    await page.getByRole("button", { name: "确认提取词条", exact: true }).click();
    await expect(forge.locator('[data-craft-equipment="10"]')).toHaveCount(0);
    await forge.getByRole("button", { name: "词条打入", exact: true }).click();
    await forge.locator('[data-craft-equipment="11"]').click();
    await forge.locator('[data-craft-affix="20"]').dragTo(forge.locator('[data-craft-slot="1"]'));
    await expect(page.getByRole("dialog", { name: "确认物品操作" })).toContainText(/金币加成.*\+50%/s);
    await page.getByRole("button", { name: "确认打入词条", exact: true }).click();
    await expect(forge.locator('[data-craft-slot="1"]')).toContainText("金币加成 +50%");
    await forge.locator('[data-craft-affix]').filter({ hasText: "攻击精粹" }).dragTo(forge.locator('[data-craft-slot="0"]'));
    await expect(page.getByRole("dialog", { name: "确认物品操作" })).toBeVisible();
    await page.getByRole("button", { name: "取消", exact: true }).click();
    await page.screenshot({ path: testInfo.outputPath("craft-affix-drag.png") });
    await forge.getByRole("button", { name: "装备继承", exact: true }).click();
    await expect(forge.locator(".craft-item-grid")).toHaveCount(1);
    await forge.locator('[data-craft-equipment="12"]').dragTo(forge.locator('[data-bench-slot="source"]'));
    await page.screenshot({ path: testInfo.outputPath("inheritance-workbench.png") });
    await page.setViewportSize({ width: 390, height: 844 });
    await forge.getByRole("button", { name: "继承全部词条", exact: true }).scrollIntoViewIfNeeded();
    await page.screenshot({ path: testInfo.outputPath("inheritance-narrow.png") });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.setViewportSize({ width: 1280, height: 720 });
    await forge.getByRole("button", { name: "继承全部词条", exact: true }).click();
    await expect(page.getByRole("dialog", { name: "确认物品操作" })).toContainText(/攻击.*\+80/s);
    await page.getByRole("button", { name: "确认装备继承", exact: true }).click();
    await expect(forge.locator('[data-craft-equipment="12"]')).toHaveCount(0);
    await forge.getByRole("button", { name: "宝珠工坊", exact: true }).click();
    await forge.locator('[data-craft-orb="30"]').click();
    await forge.getByRole("button", { name: "分解", exact: true }).click();
    await forge.getByRole("button", { name: "分解宝珠", exact: true }).click();
    await page.getByRole("button", { name: "确认分解物品", exact: true }).click();
    await expect(forge.locator('[data-craft-orb="30"]')).toHaveCount(0);
    await page.getByRole("button", { name: "关闭打造", exact: true }).click();
    await page.keyboard.press("KeyL");
    const spirit = page.getByRole("dialog", { name: "灵境", exact: true });
    await spirit.getByRole("button", { name: "注入灵魂", exact: true }).click();
    await expect(spirit.locator(".window-meta")).toContainText("1 阶");
    await expect(spirit.getByRole("button", { name: /力量/ })).toContainText("+1");
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: testInfo.outputPath("spirit-narrow.png") });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.reload({ waitUntil: "domcontentloaded" });
    await page.getByRole("button", { name: "开始新游戏", exact: true }).click();
    await enterWilds(page);
    await expect(page.locator(".survivor")).toHaveAttribute("data-state", "ready", { timeout: 30_000 });
    await pauseCombat(page); await page.keyboard.press("KeyL");
    await expect(spirit.locator(".window-meta")).toContainText("1 阶");
    await page.evaluate(async () => { const session = window.survivorApplication!.session; session.dispatch({ type: "restart" }); await session.settled; });
    await expect(page.locator(".survivor")).toHaveAttribute("data-state", "ready", { timeout: 30_000 });
    await page.keyboard.press("KeyL"); await expect(spirit.locator(".window-meta")).toContainText("1 阶");
    const other = await page.context().newPage();
    await other.goto("/", { waitUntil: "domcontentloaded" });
    await other.getByRole("button", { name: "开始新游戏", exact: true }).click();
    await expect(other.getByRole("alert")).toContainText("另一个荒原页面正在使用灵境存档", { timeout: 30_000 });
    await other.close();
    await expect(page.locator(".survivor")).toHaveAttribute("data-state", "ready");
    expect(errors).toEqual([]);
    await page.evaluate(() => window.survivorApplication!.dispose());
});
