import { expect, test } from "@playwright/test";
import type { CombatSimulation } from "../../src/core/CombatSimulation";
import { inspectCombatWorker, combatWorker, pauseCombat, advanceCombat } from "../helpers/browserCombat";
import { isBrowserConsoleFailure } from "../helpers/browserConsole";

test("utility actives and permanent passives have independent slots, previews, home equip and saved effects", async ({ page }, info) => {
    test.setTimeout(120_000); await page.setViewportSize({ width: 2560, height: 1440 });
    const errors: string[] = [];
    page.on("pageerror", error => errors.push(error.message));
    page.on("console", message => { if (isBrowserConsoleFailure(message.type(), message.text())) errors.push(message.text()); });
    await inspectCombatWorker(page); await page.goto("/", { waitUntil: "domcontentloaded" });
    await page.getByRole("button", { name: "开始新游戏", exact: true }).click();
    await expect(page.locator(".survivor[data-state=ready]")).toHaveAttribute("data-location", "homestead", { timeout: 45_000 });
    await pauseCombat(page); await page.keyboard.press("KeyK");
    const panel = page.getByRole("dialog", { name: "技能", exact: true });
    await panel.getByRole("navigation", { name: "技能学派" }).getByRole("button", { name: "通用 主动 / 被动", exact: true }).click();
    await expect(panel.locator("[data-node]")).toHaveCount(12);
    await expect(panel.locator(".constellation-node.active")).toHaveCount(3);
    await expect(panel.locator(".constellation-node.slotted-passive")).toHaveCount(9);
    await expect(panel.getByRole("group", { name: "被动装配槽" }).locator('[data-locked="true"]')).toHaveCount(3);
    await combatWorker(page).evaluate(() => {
        const sim = (self as unknown as { fixtureSimulation: CombatSimulation }).fixtureSimulation, cp = sim.checkpoint();
        sim.restore({ ...cp, player: { ...cp.player, level: 150 }, skills: { ...cp.skills, points: 149 } });
    });
    await advanceCombat(page);
    await expect(panel.locator('.panel-passives [data-locked="false"]')).toHaveCount(3);
    await panel.locator('[data-node="passive.magnet"]').hover(); await expect(page.getByRole("tooltip")).toContainText("不受距离限制");
    await panel.locator('[data-node="passive.magnet"]').click(); await panel.getByRole("button", { name: "提升万象牵引", exact: true }).click();
    await expect(panel.getByRole("button", { name: "装入被动槽 1", exact: true })).toBeDisabled();
    await panel.getByRole("button", { name: "应用构筑", exact: true }).click();
    await panel.getByRole("button", { name: "装入被动槽 1", exact: true }).click();
    await expect(panel.locator('[data-node="passive.magnet"]')).toHaveClass(/equipped/);
    await expect(page.getByRole("group", { name: "常驻被动", exact: true })).toContainText("万象牵引");
    await panel.locator('[data-node="passive.fortune"]').click();
    await panel.getByRole("button", { name: "提升寻宝直觉", exact: true }).click({ clickCount: 3 });
    await expect(panel.locator(".constellation-details .passive-numbers")).toContainText("+0 → +36");
    await expect(panel.locator(".constellation-details .power-down")).toContainText("−3%");
    await panel.getByRole("button", { name: "应用构筑", exact: true }).click(); await panel.getByRole("button", { name: "装入被动槽 2", exact: true }).click();
    await expect(panel.locator('[data-node="passive.fortune"]')).toHaveClass(/equipped/);
    const saved = await combatWorker(page).evaluate(() => {
        const sim = (self as unknown as { fixtureSimulation: CombatSimulation }).fixtureSimulation, cp = sim.checkpoint();
        sim.restore(cp); return { cp, ratings: sim.getSnapshot().player.lootProfile.ratings, bonuses: sim.getSnapshot().player.passiveBonuses };
    });
    expect(saved.cp.version).toBe(10); expect(saved.cp.skills.passives).toEqual(["magnet", "fortune", null]);
    expect(saved.ratings.quality).toBe(36); expect(saved.bonuses.damageIncrease).toBeCloseTo(-.03);
    await advanceCombat(page); await expect(panel.getByRole("group", { name: "技能装配槽" }).locator(".loadout-slot")).toHaveCount(6);
    const box = (await panel.boundingBox())!; expect(Math.abs(box.x + box.width / 2 - 1280)).toBeLessThan(2);
    await page.screenshot({ path: info.outputPath("utility-passives-2k.png") });
    await page.setViewportSize({ width: 390, height: 844 });
    await expect(panel.getByRole("button", { name: "关闭技能", exact: true })).toBeInViewport();
    await expect(panel.locator(".panel-passives")).toBeInViewport();
    await page.screenshot({ path: info.outputPath("utility-passives-narrow.png") });
    await panel.getByRole("button", { name: "卸下寻宝直觉", exact: true }).click();
    await expect(panel.locator('[data-node="passive.fortune"]')).not.toHaveClass(/equipped/);
    await panel.getByRole("button", { name: "免费洗点", exact: true }).click();
    await expect(panel.locator(".skill-points")).toHaveAttribute("data-points", "149");
    await panel.getByRole("button", { name: "关闭技能", exact: true }).click();
    await expect(page.getByRole("group", { name: "常驻被动", exact: true })).not.toContainText("万象牵引");
    expect(errors).toEqual([]);
});
