import { mkdir, writeFile, cp } from "node:fs/promises";
import { resolve } from "node:path";
import { Color, Float32BufferAttribute, SRGBColorSpace, Vector3 } from "three";
import { OBJLoader } from "three/examples/jsm/loaders/OBJLoader.js";
import { mergeGeometries, mergeVertices } from "three/examples/jsm/utils/BufferGeometryUtils.js";
import sharp from "sharp";
import { sourceReader } from "./actor-source.mjs";

/** Bake the CC0 palette into vertices: four static meshes, no runtime textures/material groups. */
export async function prepareSurvivorLoot(input, output) {
    const read = await sourceReader(input);
    const palette = await sharp(await read("colormap.png")).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
    const color = new Color(), models = {};
    for (const [name, span] of [["chest", .85], ["potion", .42], ["weapon-sword", .62], ["shield-round", .48]]) {
        const scene = new OBJLoader().parse((await read(`${name}.obj`)).toString("utf8"));
        scene.updateMatrixWorld(true);
        const parts = [];
        scene.traverse(mesh => {
            if (!mesh.isMesh) return;
            const geometry = mesh.geometry.clone().applyMatrix4(mesh.matrixWorld), uv = geometry.getAttribute("uv");
            const colors = new Float32Array(uv.count * 3);
            for (let i = 0; i < uv.count; i++) {
                const x = Math.max(0, Math.min(palette.info.width - 1, Math.floor(uv.getX(i) * palette.info.width)));
                const y = Math.max(0, Math.min(palette.info.height - 1, Math.floor((1 - uv.getY(i)) * palette.info.height)));
                const pixel = (y * palette.info.width + x) * 4;
                color.setRGB(palette.data[pixel] / 255, palette.data[pixel + 1] / 255, palette.data[pixel + 2] / 255, SRGBColorSpace);
                color.toArray(colors, i * 3);
            }
            geometry.setAttribute("color", new Float32BufferAttribute(colors, 3)); geometry.deleteAttribute("uv"); geometry.clearGroups();
            parts.push(geometry); mesh.geometry.dispose(); mesh.material.dispose();
        });
        const merged = mergeGeometries(parts), geometry = mergeVertices(merged);
        for (const part of parts) part.dispose(); merged.dispose();
        geometry.computeBoundingBox();
        const center = geometry.boundingBox.getCenter(new Vector3()), size = geometry.boundingBox.getSize(new Vector3());
        geometry.translate(-center.x, -geometry.boundingBox.min.y, -center.z);
        geometry.scale(...Array(3).fill(span / Math.max(size.x, size.y, size.z)));
        // Stable generated bytes: runtime identities are allocated when parsed.
        const json = geometry.toJSON(); delete json.uuid; models[name] = json;
        geometry.dispose();
    }
    await read("License.txt");
    await mkdir(output, { recursive: true });
    await writeFile(resolve(output, "models.json"), JSON.stringify(models));
    for (const file of ["License.txt", "sources.json"]) await cp(resolve(input, file), resolve(output, file));
}
