// Generated by scripts/lib/survivor-actors.mjs; same normalized hand as the baked release pose.
export const SHAMAN_CAST_SOCKET = [0.0684768358169093,0.9766862412593774,0.45354665731341287] as const;
